domain,problem,algorithm,unexplained_errors,error,raw_memory,p7_settings_file,cost,coverage,dead_ends,evaluations,expansions,generated,initial_h_value,plan_length,planner_time,search_time,translator_facts,reformulation_time,reformulated_plan_valid,rebuild_plan_valid,solvable,plan_length_difference,macros_used,macros_generated
depot_easy,p01.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,10.0,1,0,86,21,132, ,10,0.04,0.01,48,5978.0,True,True,True,0,0,0
depot_easy,p02.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10804,depot_walker_sameoutput,16.0,1,0,174,43,327, ,16,0.061335400000000005,0.01,86,6878.0,True,True,True,0,0,0
depot_easy,p03.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12256,depot_walker_sameoutput,51.0,1,0,1870,467,3706, ,51,0.1385837,0.067916,132,9274.0,True,True,True,0,0,0
depot_easy,p04.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12860,depot_walker_sameoutput,80.0,1,0,4346,1086,9459, ,80,0.296578,0.168766,208,9667.0,True,True,True,0,0,0
depot_easy,p07.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12248,depot_walker_sameoutput,30.0,1,0,342,85,772, ,30,0.1033971,0.0125906,156,9355.0,True,True,True,0,0,0
depot_easy,p08.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16008,depot_walker_sameoutput,45.0,1,0,1642,410,4761, ,45,0.345804,0.157887,284,11707.0,True,True,True,0,0,0
depot_easy,p13.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15756,depot_walker_sameoutput,28.0,1,0,426,106,1612, ,28,0.2483884,0.0382049,236,27253.0,True,True,True,0,0,0
depot_easy,p14.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24056,depot_walker_sameoutput,49.0,1,0,726,181,3349, ,49,0.552536,0.1437,404,30072.0,True,True,True,0,0,0
depot_easy,p16.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17604,depot_walker_sameoutput,34.0,1,0,718,179,4091, ,34,0.328086,0.0695324,240,18352.0,True,True,True,0,0,0
depot_easy,p19.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,25716,depot_walker_sameoutput,56.0,1,0,1534,383,13526, ,56,0.794241,0.355629,388,44250.0,True,True,True,0,0,0
driverlog_easy,p01.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10272,depot_walker_sameoutput,8.0,1,0,38,9,61, ,8,0.03,0.01,34,4696.0,True,False,True,-8,8,0
driverlog_easy,p02.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,11236,depot_walker_sameoutput,21.0,1,0,21838,5459,44791, ,21,0.120077,0.0965338,41,6496.0,True,False,True,-21,21,0
driverlog_easy,p03.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10272,depot_walker_sameoutput,15.0,1,0,130,32,226, ,15,0.03,0.01,41,6172.0,True,False,True,-15,15,0
driverlog_easy,p04.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,11320,depot_walker_sameoutput,25.0,1,0,17982,4495,48198, ,25,0.1014759,0.0889015,51,8228.0,True,False,True,-25,25,0
driverlog_easy,p05.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10404,depot_walker_sameoutput,22.0,1,0,238,59,678, ,22,0.04,0.01,59,7689.0,True,False,True,-22,22,0
driverlog_easy,p06.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10540,depot_walker_sameoutput,15.0,1,0,2122,530,7060, ,15,0.0470024,0.012879,69,12119.0,True,False,True,-15,15,0
driverlog_easy,p07.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10404,depot_walker_sameoutput,17.0,1,0,158,39,512, ,17,0.04,0.01,78,14411.0,True,False,True,-17,17,0
driverlog_easy,p08.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10800,depot_walker_sameoutput,27.0,1,0,4722,1180,19035, ,27,0.0657198,0.0323123,84,15527.0,True,False,True,-27,27,0
driverlog_easy,p09.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,11056,depot_walker_sameoutput,49.0,1,0,4850,1212,13521, ,49,0.0811457,0.0365437,97,15763.0,True,False,True,-49,49,0
driverlog_easy,p10.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10668,depot_walker_sameoutput,21.0,1,0,262,65,891, ,21,0.04,0.01,114,15218.0,True,False,True,-21,21,0
driverlog_easy,p11.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10800,depot_walker_sameoutput,27.0,1,0,358,89,1200, ,27,0.0718003,0.01,119,16390.0,True,False,True,-27,27,0
driverlog_easy,p12.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,16080,depot_walker_sameoutput,41.0,1,0,49374,12343,167915, ,41,0.713826,0.626555,176,18871.0,True,False,True,-41,41,0
driverlog_easy,p13.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,12520,depot_walker_sameoutput,41.0,1,0,7590,1897,27491, ,41,0.24210399999999999,0.124564,197,17156.0,True,False,True,-41,41,0
driverlog_easy,p14.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,13308,depot_walker_sameoutput,56.0,1,0,13718,3429,56204, ,56,0.35506099999999996,0.255875,195,19692.0,True,False,True,-56,56,0
driverlog_easy,p15.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,14012,depot_walker_sameoutput,53.0,1,0,926,231,4235, ,53,0.2885787,0.052829,336,33144.0,True,False,True,-53,53,0
driverlog_easy,p17.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,22952,depot_walker_sameoutput,123.0,1,0,4714,1178,37225, ,123,1.016189,0.516495,665,52680.0,True,False,True,-123,123,0
freecell_easy,p01.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,p02.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,p03.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,p04.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,p05.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,p06.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,p07.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,probfreecell-2-1.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,probfreecell-2-2.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,probfreecell-2-3.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,probfreecell-2-4.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,probfreecell-2-5.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,probfreecell-3-1.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,probfreecell-3-2.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,probfreecell-3-3.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,probfreecell-3-4.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
freecell_easy,probfreecell-3-5.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
gripper,prob01.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,13.0,1,0,82,20,91, ,13,0.24000000000000002,0.01,22,930.0,True,True,True,2,1,0
gripper,prob02.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,20.0,1,0,174,43,216, ,20,0.22,0.01,34,1259.0,True,True,True,1,1,0
gripper,prob03.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,29.0,1,0,154,38,251, ,29,0.05,0.01,44,1204.0,True,True,True,0,0,0
gripper,prob04.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10408,depot_walker_sameoutput,35.0,1,0,1442,360,1760, ,35,0.2421723,0.01,46,1872.0,True,True,True,2,1,0
gripper,prob05.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,45.0,1,0,522,130,808, ,45,0.27,0.01,54,2233.0,True,True,True,0,0,0
gripper,prob06.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10660,depot_walker_sameoutput,53.0,1,0,290,72,795, ,53,0.24000000000000002,0.01,74,2487.0,True,True,True,0,0,0
gripper,prob07.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10792,depot_walker_sameoutput,61.0,1,0,314,78,891, ,61,0.04,0.01,84,2756.0,True,True,True,0,0,0
gripper,prob08.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11040,depot_walker_sameoutput,69.0,1,0,354,88,1111, ,69,0.031021899999999998,0.01,94,2824.0,True,True,True,0,0,0
gripper,prob09.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11184,depot_walker_sameoutput,77.0,1,0,394,98,1357, ,77,0.0431338,0.01,104,3420.0,True,True,True,0,0,0
gripper,prob10.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11444,depot_walker_sameoutput,85.0,1,0,434,108,1623, ,85,0.0447585,0.0102479,114,3778.0,True,True,True,0,0,0
gripper,prob11.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11568,depot_walker_sameoutput,93.0,1,0,474,118,1915, ,93,0.043537599999999996,0.011666,124,4512.0,True,True,True,0,0,0
gripper,prob12.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11824,depot_walker_sameoutput,101.0,1,0,514,128,2231, ,101,0.0431498,0.0101428,134,4585.0,True,True,True,0,0,0
gripper,prob13.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12084,depot_walker_sameoutput,109.0,1,0,554,138,2571, ,109,0.0582682,0.0159336,144,5580.0,True,True,True,0,0,0
gripper,prob14.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12228,depot_walker_sameoutput,117.0,1,0,594,148,2935, ,117,0.0619087,0.0171569,154,6812.0,True,True,True,0,0,0
gripper,prob15.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12548,depot_walker_sameoutput,125.0,1,0,634,158,3323, ,125,0.0640038,0.0185561,164,6946.0,True,True,True,0,0,0
gripper,prob16.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13148,depot_walker_sameoutput,133.0,1,0,674,168,3735, ,133,0.0549273,0.0198955,174,7535.0,True,True,True,0,0,0
gripper,prob17.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13528,depot_walker_sameoutput,141.0,1,0,714,178,4171, ,141,0.0680846,0.0226693,184,8234.0,True,True,True,0,0,0
gripper,prob18.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13772,depot_walker_sameoutput,149.0,1,0,754,188,4631, ,149,0.0893646,0.0243481,194,9139.0,True,True,True,0,0,0
gripper,prob19.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14024,depot_walker_sameoutput,157.0,1,0,794,198,5115, ,157,0.07324810000000001,0.0270047,204,9300.0,True,True,True,0,0,0
gripper,prob20.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14348,depot_walker_sameoutput,165.0,1,0,834,208,5623, ,165,0.0734947,0.0280829,214,10031.0,True,True,True,0,0,0
hanoi,pb1.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
hanoi,pb2.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
hanoi,pb3.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
hanoi,pb4.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
hanoi,pb5.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
hanoi,pb6.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
logistics_easy,p01.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,14240,depot_walker_sameoutput,32.0,1,0,430,107,16192, ,32,0.2822986,0.0261701,559,48163.0,True,False,True,-32,32,0
logistics_easy,p02.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,19132,depot_walker_sameoutput,53.0,1,0,1618,404,79921, ,53,0.613537,0.155155,1206,71046.0,True,False,True,-53,53,0
logistics_easy,p03.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,26572,depot_walker_sameoutput,81.0,1,0,2754,688,179477, ,81,0.729868,0.263929,2175,95513.0,True,False,True,-81,81,0
miconic,s1-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,4.0,1,0,18,4,7, ,4,0.02,0.01,8,369.0,True,True,True,0,0,0
miconic,s1-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,3.0,1,0,14,3,6, ,3,0.02,0.01,8,333.0,True,True,True,0,0,0
miconic,s1-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,4.0,1,0,18,4,7, ,4,0.03,0.01,8,359.0,True,True,True,0,0,0
miconic,s1-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,4.0,1,0,18,4,7, ,4,0.03,0.01,8,323.0,True,True,True,0,0,0
miconic,s1-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,4.0,1,0,18,4,7, ,4,0.03,0.01,8,324.0,True,True,True,0,0,0
miconic,s10-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11168,depot_walker_sameoutput,47.0,1,0,574,143,2833, ,47,0.0513736,0.01,60,17233.0,True,True,True,0,0,0
miconic,s10-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11044,depot_walker_sameoutput,41.0,1,0,462,115,2296, ,41,0.05,0.01,60,17791.0,True,True,True,0,0,0
miconic,s10-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11044,depot_walker_sameoutput,45.0,1,0,518,129,2593, ,45,0.0405573,0.01,60,16830.0,True,True,True,0,0,0
miconic,s10-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11312,depot_walker_sameoutput,38.0,1,0,450,112,2249, ,38,0.0408024,0.01,60,17137.0,True,True,True,0,0,0
miconic,s10-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11036,depot_walker_sameoutput,43.0,1,0,474,118,2352, ,43,0.041225899999999996,0.01,60,17418.0,True,True,True,0,0,0
miconic,s11-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11328,depot_walker_sameoutput,54.0,1,0,758,189,4156, ,54,0.054577600000000004,0.0100151,66,18454.0,True,True,True,0,0,0
miconic,s11-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11196,depot_walker_sameoutput,49.0,1,0,546,136,3016, ,49,0.0526349,0.01,66,18667.0,True,True,True,0,0,0
miconic,s11-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11464,depot_walker_sameoutput,57.0,1,0,858,214,4657, ,57,0.055597400000000005,0.0109498,66,18879.0,True,True,True,0,0,0
miconic,s11-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11460,depot_walker_sameoutput,47.0,1,0,606,151,3305, ,47,0.0510441,0.01,66,18949.0,True,True,True,0,0,0
miconic,s11-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11332,depot_walker_sameoutput,46.0,1,0,718,179,3954, ,46,0.0534794,0.01,66,18721.0,True,True,True,0,0,0
miconic,s12-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11724,depot_walker_sameoutput,48.0,1,0,554,138,3317, ,48,0.053426,0.01,72,20326.0,True,True,True,0,0,0
miconic,s12-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11596,depot_walker_sameoutput,54.0,1,0,706,176,4232, ,54,0.0658778,0.0109411,72,20082.0,True,True,True,0,0,0
miconic,s12-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11592,depot_walker_sameoutput,57.0,1,0,846,211,5045, ,57,0.0660187,0.0116051,72,20909.0,True,True,True,0,0,0
miconic,s12-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11460,depot_walker_sameoutput,54.0,1,0,738,184,4411, ,54,0.04,0.01,72,15900.0,True,True,True,0,0,0
miconic,s12-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11724,depot_walker_sameoutput,61.0,1,0,966,241,5728, ,61,0.0577022,0.0136583,72,20947.0,True,True,True,0,0,0
miconic,s13-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11852,depot_walker_sameoutput,55.0,1,0,846,211,5490, ,55,0.0682513,0.0135486,78,22101.0,True,True,True,0,0,0
miconic,s13-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11720,depot_walker_sameoutput,59.0,1,0,910,227,5901, ,59,0.0791561,0.013666,78,22084.0,True,True,True,0,0,0
miconic,s13-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12120,depot_walker_sameoutput,64.0,1,0,934,233,6007, ,64,0.0803866,0.0177589,78,22837.0,True,True,True,0,0,0
miconic,s13-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11852,depot_walker_sameoutput,56.0,1,0,674,168,4365, ,56,0.0663368,0.0110527,78,21879.0,True,True,True,0,0,0
miconic,s13-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11720,depot_walker_sameoutput,53.0,1,0,838,209,5457, ,53,0.0683873,0.012949,78,21129.0,True,True,True,0,0,0
miconic,s14-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12008,depot_walker_sameoutput,55.0,1,0,810,202,5634, ,55,0.0802565,0.0139741,84,22970.0,True,True,True,0,0,0
miconic,s14-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12268,depot_walker_sameoutput,68.0,1,0,1034,258,7223, ,68,0.0925692,0.016889,84,22688.0,True,True,True,0,0,0
miconic,s14-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12396,depot_walker_sameoutput,67.0,1,0,1094,273,7611, ,67,0.07196330000000001,0.019076,84,23319.0,True,True,True,0,0,0
miconic,s14-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11752,depot_walker_sameoutput,55.0,1,0,762,190,5379, ,55,0.0783159,0.0133461,84,22746.0,True,True,True,0,0,0
miconic,s14-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12124,depot_walker_sameoutput,65.0,1,0,878,219,6135, ,65,0.0686505,0.0146494,84,23878.0,True,True,True,0,0,0
miconic,s15-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12232,depot_walker_sameoutput,61.0,1,0,962,240,7231, ,61,0.0921864,0.0199686,90,24646.0,True,True,True,0,0,0
miconic,s15-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13140,depot_walker_sameoutput,75.0,1,0,1426,356,10622, ,75,0.0904225,0.0241776,90,23528.0,True,True,True,0,0,0
miconic,s15-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12900,depot_walker_sameoutput,69.0,1,0,1214,303,9059, ,69,0.0962374,0.0215663,90,23961.0,True,True,True,0,0,0
miconic,s15-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12616,depot_walker_sameoutput,68.0,1,0,1182,295,8820, ,68,0.09714120000000001,0.020969,90,24384.0,True,True,True,0,0,0
miconic,s15-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12232,depot_walker_sameoutput,69.0,1,0,1042,260,7825, ,69,0.0945501,0.0190012,90,24946.0,True,True,True,0,0,0
miconic,s16-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11324,depot_walker_sameoutput,74.0,1,0,1382,345,11005, ,74,0.1234379,0.0347666,128,25726.0,True,True,True,0,0,0
miconic,s16-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11200,depot_walker_sameoutput,68.0,1,0,1062,265,8480, ,68,0.1261879,0.0273856,128,24632.0,True,True,True,0,0,0
miconic,s16-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11320,depot_walker_sameoutput,76.0,1,0,1382,345,10992, ,76,0.1341571,0.0356275,128,25250.0,True,True,True,0,0,0
miconic,s16-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11196,depot_walker_sameoutput,69.0,1,0,1226,306,9850, ,69,0.1397426,0.032041,128,24796.0,True,True,True,0,0,0
miconic,s16-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11196,depot_walker_sameoutput,72.0,1,0,1194,298,9532, ,72,0.1287307,0.0302848,128,24246.0,True,True,True,0,0,0
miconic,s17-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15144,depot_walker_sameoutput,76.0,1,0,1758,439,14920, ,76,0.1411629,0.0347001,102,26888.0,True,True,True,0,0,0
miconic,s17-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14884,depot_walker_sameoutput,77.0,1,0,1390,347,11820, ,77,0.1248533,0.0276848,102,27239.0,True,True,True,0,0,0
miconic,s17-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14880,depot_walker_sameoutput,78.0,1,0,1470,367,12508, ,78,0.124956,0.029671,102,27409.0,True,True,True,0,0,0
miconic,s17-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15800,depot_walker_sameoutput,84.0,1,0,1718,429,14511, ,84,0.1201532,0.035256,102,27553.0,True,True,True,0,0,0
miconic,s17-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14864,depot_walker_sameoutput,68.0,1,0,1230,307,10483, ,68,0.12287509999999999,0.0261139,102,26737.0,True,True,True,0,0,0
miconic,s18-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15812,depot_walker_sameoutput,80.0,1,0,1506,376,13541, ,80,0.1380153,0.0301994,108,28357.0,True,True,True,0,0,0
miconic,s18-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15540,depot_walker_sameoutput,78.0,1,0,1406,351,12684, ,78,0.1299738,0.0316512,108,28811.0,True,True,True,0,0,0
miconic,s18-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15540,depot_walker_sameoutput,83.0,1,0,1562,390,14059, ,83,0.12057029999999999,0.0331082,108,27925.0,True,True,True,0,0,0
miconic,s18-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16044,depot_walker_sameoutput,83.0,1,0,1686,421,15115, ,83,0.13222509999999998,0.0353295,108,28842.0,True,True,True,0,0,0
miconic,s18-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15140,depot_walker_sameoutput,84.0,1,0,1674,418,15033, ,84,0.1312449,0.0335075,108,29045.0,True,True,True,0,0,0
miconic,s19-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16412,depot_walker_sameoutput,83.0,1,0,1730,432,16460, ,83,0.1561986,0.038707,114,29268.0,True,True,True,0,0,0
miconic,s19-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17080,depot_walker_sameoutput,80.0,1,0,1626,406,15396, ,80,0.1445684,0.0367287,114,29950.0,True,True,True,0,0,0
miconic,s19-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16408,depot_walker_sameoutput,94.0,1,0,1938,484,18349, ,94,0.14904710000000002,0.0406757,114,29572.0,True,True,True,0,0,0
miconic,s19-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16676,depot_walker_sameoutput,91.0,1,0,1974,493,18766, ,91,0.1585238,0.0408702,114,29664.0,True,True,True,0,0,0
miconic,s19-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16400,depot_walker_sameoutput,86.0,1,0,1774,443,16838, ,86,0.1475273,0.0400564,114,29832.0,True,True,True,0,0,0
miconic,s2-0.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10272,depot_walker_sameoutput,8.0,1,0,38,9,37, ,8,0.04,0.01,16,864.0,True,False,True,2,1,0
miconic,s2-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,7.0,1,0,94,23,90, ,7,0.04,0.01,16,923.0,True,True,True,0,0,0
miconic,s2-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,7.0,1,0,62,15,60, ,7,0.05,0.01,16,826.0,True,True,True,0,0,0
miconic,s2-3.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10272,depot_walker_sameoutput,7.0,1,0,38,9,37, ,7,0.04,0.01,16,891.0,True,False,True,2,1,0
miconic,s2-4.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10272,depot_walker_sameoutput,8.0,1,0,86,21,83, ,8,0.04,0.01,16,877.0,True,False,True,2,1,0
miconic,s20-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16748,depot_walker_sameoutput,86.0,1,0,1766,441,17653, ,86,0.1602082,0.0424255,120,29995.0,True,True,True,0,0,0
miconic,s20-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17280,depot_walker_sameoutput,95.0,1,0,2082,520,20745, ,95,0.16658889999999998,0.0482689,120,32378.0,True,True,True,0,0,0
miconic,s20-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16340,depot_walker_sameoutput,89.0,1,0,1826,456,18294, ,89,0.171255,0.0422444,120,30084.0,True,True,True,0,0,0
miconic,s20-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16480,depot_walker_sameoutput,95.0,1,0,1818,454,18296, ,95,0.1716646,0.0425884,120,31194.0,True,True,True,0,0,0
miconic,s20-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16744,depot_walker_sameoutput,85.0,1,0,1830,457,18323, ,85,0.1730931,0.0449947,120,30214.0,True,True,True,0,0,0
miconic,s21-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17864,depot_walker_sameoutput,103.0,1,0,2098,524,21943, ,103,0.19331710000000002,0.0533227,126,32536.0,True,True,True,0,0,0
miconic,s21-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17884,depot_walker_sameoutput,100.0,1,0,2302,575,24222, ,100,0.1972875,0.057692,126,31302.0,True,True,True,0,0,0
miconic,s21-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17764,depot_walker_sameoutput,96.0,1,0,1730,432,18161, ,96,0.1937759,0.045047,126,32026.0,True,True,True,0,0,0
miconic,s21-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17216,depot_walker_sameoutput,92.0,1,0,2154,538,22548, ,92,0.1919331,0.0521503,126,31454.0,True,True,True,0,0,0
miconic,s21-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18016,depot_walker_sameoutput,92.0,1,0,1782,445,18726, ,92,0.1837781,0.0448575,126,33737.0,True,True,True,0,0,0
miconic,s22-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18756,depot_walker_sameoutput,109.0,1,0,2902,725,31850, ,109,0.2251381,0.0756669,132,33238.0,True,True,True,0,0,0
miconic,s22-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18084,depot_walker_sameoutput,104.0,1,0,2406,601,26438, ,104,0.21480390000000002,0.064205,132,33625.0,True,True,True,0,0,0
miconic,s22-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18360,depot_walker_sameoutput,102.0,1,0,2594,648,28517, ,102,0.21970280000000003,0.0691066,132,32737.0,True,True,True,0,0,0
miconic,s22-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19440,depot_walker_sameoutput,102.0,1,0,2818,704,30893, ,102,0.21240910000000002,0.0726641,132,32966.0,True,True,True,0,0,0
miconic,s22-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19024,depot_walker_sameoutput,101.0,1,0,2362,590,25971, ,101,0.2132476,0.0635443,132,33921.0,True,True,True,0,0,0
miconic,s23-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19372,depot_walker_sameoutput,110.0,1,0,2858,714,32841, ,110,0.2419931,0.0809741,138,34028.0,True,True,True,0,0,0
miconic,s23-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19104,depot_walker_sameoutput,105.0,1,0,2698,674,30995, ,105,0.22400000000000003,0.0738057,138,34234.0,True,True,True,0,0,0
miconic,s23-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18600,depot_walker_sameoutput,89.0,1,0,1942,485,22475, ,89,0.2151746,0.0541015,138,33460.0,True,True,True,0,0,0
miconic,s23-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18460,depot_walker_sameoutput,100.0,1,0,2458,614,28373, ,100,0.21976110000000001,0.0684476,138,34989.0,True,True,True,0,0,0
miconic,s23-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19252,depot_walker_sameoutput,107.0,1,0,2506,626,28784, ,107,0.24138320000000002,0.0711292,138,33756.0,True,True,True,0,0,0
miconic,s24-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19976,depot_walker_sameoutput,97.0,1,0,1854,463,22230, ,97,0.2394158,0.0571626,144,34957.0,True,True,True,0,0,0
miconic,s24-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20008,depot_walker_sameoutput,118.0,1,0,2814,703,33799, ,118,0.1446715,0.0479826,144,22788.0,True,True,True,0,0,0
miconic,s24-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20948,depot_walker_sameoutput,113.0,1,0,3238,809,38776, ,113,0.265825,0.0938431,144,34145.0,True,True,True,0,0,0
miconic,s24-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20396,depot_walker_sameoutput,112.0,1,0,2946,736,35321, ,112,0.2662471,0.0870318,144,35088.0,True,True,True,0,0,0
miconic,s24-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19996,depot_walker_sameoutput,115.0,1,0,3262,815,39113, ,115,0.273977,0.0927032,144,34717.0,True,True,True,0,0,0
miconic,s25-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20944,depot_walker_sameoutput,110.0,1,0,2502,625,31260, ,110,0.2699633,0.0781665,150,35073.0,True,True,True,0,0,0
miconic,s25-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22080,depot_walker_sameoutput,128.0,1,0,3670,917,45740, ,128,0.30797399999999997,0.115314,150,35946.0,True,True,True,0,0,0
miconic,s25-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20036,depot_walker_sameoutput,111.0,1,0,2870,717,36023, ,111,0.280701,0.0892027,150,36279.0,True,True,True,0,0,0
miconic,s25-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,21740,depot_walker_sameoutput,118.0,1,0,3250,812,40469, ,118,0.296091,0.103741,150,35484.0,True,True,True,0,0,0
miconic,s25-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,21228,depot_walker_sameoutput,124.0,1,0,3338,834,41667, ,124,0.295041,0.103306,150,35537.0,True,True,True,0,0,0
miconic,s26-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,21392,depot_walker_sameoutput,128.0,1,0,3370,842,43724, ,128,0.311587,0.108942,156,36485.0,True,True,True,0,0,0
miconic,s26-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,21400,depot_walker_sameoutput,117.0,1,0,3302,825,42998, ,117,0.310431,0.109741,156,35807.0,True,True,True,0,0,0
miconic,s26-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23784,depot_walker_sameoutput,130.0,1,0,3670,917,47573, ,130,0.31503899999999996,0.122015,156,36838.0,True,True,True,0,0,0
miconic,s26-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22892,depot_walker_sameoutput,127.0,1,0,3774,943,48970, ,127,0.34029,0.126799,156,36522.0,True,True,True,0,0,0
miconic,s26-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20880,depot_walker_sameoutput,113.0,1,0,2586,646,33670, ,113,0.2813342,0.0780908,156,36778.0,True,True,True,0,0,0
miconic,s27-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24268,depot_walker_sameoutput,138.0,1,0,4518,1129,60944, ,138,0.381496,0.157651,162,36923.0,True,True,True,0,0,0
miconic,s27-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23732,depot_walker_sameoutput,124.0,1,0,3818,954,51488, ,124,0.35897599999999996,0.134384,162,36893.0,True,True,True,0,0,0
miconic,s27-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22824,depot_walker_sameoutput,136.0,1,0,4322,1080,58279, ,136,0.37181,0.147406,162,37631.0,True,True,True,0,0,0
miconic,s27-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23192,depot_walker_sameoutput,132.0,1,0,3742,935,50427, ,132,0.374247,0.13986,162,38269.0,True,True,True,0,0,0
miconic,s27-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22972,depot_walker_sameoutput,120.0,1,0,3950,987,53359, ,120,0.360214,0.136765,162,37187.0,True,True,True,0,0,0
miconic,s28-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,25012,depot_walker_sameoutput,138.0,1,0,4786,1196,66750, ,138,0.416422,0.183105,168,37839.0,True,True,True,0,0,0
miconic,s28-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23984,depot_walker_sameoutput,127.0,1,0,3602,900,50486, ,127,0.354267,0.130442,168,38020.0,True,True,True,0,0,0
miconic,s28-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24508,depot_walker_sameoutput,138.0,1,0,4254,1063,59504, ,138,0.399427,0.164916,168,38585.0,True,True,True,0,0,0
miconic,s28-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22116,depot_walker_sameoutput,121.0,1,0,2834,708,39852, ,121,0.34104,0.105816,168,39504.0,True,True,True,0,0,0
miconic,s28-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24236,depot_walker_sameoutput,130.0,1,0,3658,914,51174, ,130,0.375357,0.140379,168,38563.0,True,True,True,0,0,0
miconic,s29-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24720,depot_walker_sameoutput,135.0,1,0,4218,1054,61165, ,135,0.41177600000000003,0.166129,174,38534.0,True,True,True,0,0,0
miconic,s29-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23812,depot_walker_sameoutput,133.0,1,0,4206,1051,61114, ,133,0.446405,0.180188,174,38397.0,True,True,True,0,0,0
miconic,s29-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,25140,depot_walker_sameoutput,131.0,1,0,3790,947,55011, ,131,0.39320299999999997,0.14722,174,39142.0,True,True,True,0,0,0
miconic,s29-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,25416,depot_walker_sameoutput,145.0,1,0,4566,1141,66072, ,145,0.428956,0.173049,174,38228.0,True,True,True,0,0,0
miconic,s29-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,26476,depot_walker_sameoutput,147.0,1,0,4830,1207,69751, ,147,0.45218899999999995,0.199121,174,38784.0,True,True,True,0,0,0
miconic,s3-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,13.0,1,0,74,18,108, ,13,0.03,0.01,24,1822.0,True,True,True,0,0,0
miconic,s3-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,14.0,1,0,82,20,118, ,14,0.02,0.01,24,1819.0,True,True,True,0,0,0
miconic,s3-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,12.0,1,0,78,19,110, ,12,0.03,0.01,24,2051.0,True,True,True,0,0,0
miconic,s3-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,10.0,1,0,70,17,103, ,10,0.02,0.01,24,1722.0,True,True,True,0,0,0
miconic,s3-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,11.0,1,0,70,17,104, ,11,0.03,0.01,24,1675.0,True,True,True,0,0,0
miconic,s30-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24740,depot_walker_sameoutput,133.0,1,0,3662,915,54891, ,133,0.2337246,0.0839638,180,27176.0,True,True,True,0,0,0
miconic,s30-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,25892,depot_walker_sameoutput,140.0,1,0,4294,1073,64408, ,140,0.452961,0.185844,180,39860.0,True,True,True,0,0,0
miconic,s30-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,26580,depot_walker_sameoutput,129.0,1,0,3738,934,56218, ,129,0.404702,0.148331,180,39951.0,True,True,True,0,0,0
miconic,s30-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,27092,depot_walker_sameoutput,142.0,1,0,4862,1215,72753, ,142,0.462172,0.195499,180,39617.0,True,True,True,0,0,0
miconic,s30-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,26452,depot_walker_sameoutput,143.0,1,0,4794,1198,71803, ,143,0.48626,0.199722,180,39637.0,True,True,True,0,0,0
miconic,s4-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,15.0,1,0,66,16,131, ,15,0.09999999999999999,0.01,32,3524.0,True,True,True,0,0,0
miconic,s4-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,14.0,1,0,66,16,137, ,14,0.09999999999999999,0.01,32,3758.0,True,True,True,0,0,0
miconic,s4-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,18.0,1,0,134,33,269, ,18,0.09999999999999999,0.01,32,3537.0,True,True,True,0,0,0
miconic,s4-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,19.0,1,0,134,33,273, ,19,0.09999999999999999,0.01,32,3581.0,True,True,True,0,0,0
miconic,s4-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,21.0,1,0,146,36,287, ,21,0.11,0.01,32,3471.0,True,True,True,0,0,0
miconic,s5-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,24.0,1,0,170,42,408, ,24,0.03,0.01,30,5495.0,True,True,True,0,0,0
miconic,s5-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,20.0,1,0,198,49,480, ,20,0.03,0.01,30,5466.0,True,True,True,0,0,0
miconic,s5-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,20.0,1,0,138,34,350, ,20,0.03,0.01,30,5442.0,True,True,True,0,0,0
miconic,s5-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,21.0,1,0,154,38,379, ,21,0.02,0.01,30,5166.0,True,True,True,0,0,0
miconic,s5-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,24.0,1,0,174,43,421, ,24,0.03,0.01,30,4859.0,True,True,True,0,0,0
miconic,s6-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,21.0,1,0,198,49,598, ,21,0.03,0.01,36,7362.0,True,True,True,0,0,0
miconic,s6-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,23.0,1,0,158,39,473, ,23,0.03,0.01,36,7837.0,True,True,True,0,0,0
miconic,s6-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,25.0,1,0,230,57,679, ,25,0.02,0.01,36,8036.0,True,True,True,0,0,0
miconic,s6-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,22.0,1,0,202,50,602, ,22,0.03,0.01,36,7586.0,True,True,True,0,0,0
miconic,s6-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,24.0,1,0,230,57,682, ,24,0.02,0.01,36,8306.0,True,True,True,0,0,0
miconic,s7-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10408,depot_walker_sameoutput,29.0,1,0,214,53,749, ,29,0.04,0.01,56,10396.0,True,True,True,0,0,0
miconic,s7-1.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10408,depot_walker_sameoutput,28.0,1,0,366,91,2344, ,28,0.03,0.01,56,10339.0,True,False,True,1,1,0
miconic,s7-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10408,depot_walker_sameoutput,23.0,1,0,190,47,675, ,23,0.03,0.01,56,10407.0,True,True,True,0,0,0
miconic,s7-3.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10408,depot_walker_sameoutput,26.0,1,0,198,49,1194, ,26,0.03,0.01,56,9898.0,True,False,True,1,1,0
miconic,s7-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10408,depot_walker_sameoutput,35.0,1,0,358,89,1224, ,35,0.03,0.01,56,10148.0,True,True,True,0,0,0
miconic,s8-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,34.0,1,0,282,70,1114, ,34,0.03,0.01,48,12501.0,True,True,True,0,0,0
miconic,s8-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,33.0,1,0,334,83,1343, ,33,0.04,0.01,48,12259.0,True,True,True,0,0,0
miconic,s8-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,34.0,1,0,358,89,1417, ,34,0.04,0.01,48,13282.0,True,True,True,0,0,0
miconic,s8-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,37.0,1,0,418,104,1657, ,37,0.04,0.01,48,12942.0,True,True,True,0,0,0
miconic,s8-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10540,depot_walker_sameoutput,30.0,1,0,330,82,1315, ,30,0.04,0.01,48,12980.0,True,True,True,0,0,0
miconic,s9-0.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10932,depot_walker_sameoutput,43.0,1,0,478,119,2114, ,43,0.05,0.01,54,14696.0,True,True,True,0,0,0
miconic,s9-1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10932,depot_walker_sameoutput,42.0,1,0,466,116,2090, ,42,0.04,0.01,54,15705.0,True,True,True,0,0,0
miconic,s9-2.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10932,depot_walker_sameoutput,40.0,1,0,518,129,2319, ,40,0.0509591,0.01,54,15068.0,True,True,True,0,0,0
miconic,s9-3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11064,depot_walker_sameoutput,35.0,1,0,378,94,1689, ,35,0.04,0.01,54,15374.0,True,True,True,0,0,0
miconic,s9-4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10800,depot_walker_sameoutput,33.0,1,0,358,89,1627, ,33,0.05,0.01,54,16025.0,True,True,True,0,0,0
mprime_easy,prob01.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob02.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob03.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob04.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob05.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob07.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob09.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob11.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob12.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob16.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob25.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob26.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob27.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob28.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob29.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob31.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob32.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob34.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mprime_easy,prob35.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob01.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob02.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob03.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob09.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob11.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob19.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob20.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob25.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob26.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob27.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob28.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob29.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
mystery_easy,prob30.pddl,regressor,"['exitcode--6', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\nterminate called after throwing an instance of \'std::logic_error\'\n  what():  Not implemented\nTraceback (most recent call last):\n  File ""../../P7LabParser.py"", line 97, in <module>\n    parser.parse()\n  File ""/home/trifoldcube/.local/lib/python3.8/site-packages/lab/parser.py"", line 215, in parse\n    function.function(content, self.props)\n  File ""../../P7LabParser.py"", line 48, in get_times\n    results = content.split(""Values\\n"")[1].split(""Total Time"")[0]\nIndexError: list index out of range\n']",exitcode--6, ,depot_walker_sameoutput, , , , , , , , , , , , , , , , , , 
satellite_easy,p01-pfile1.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,9.0,1,0,38,9,71, ,9,0.14,0.01,17,1188.0,True,True,True,0,0,0
satellite_easy,p02-pfile2.pddl,regressor,"['Rebuild plan was not valid!', 'run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n']",success,10404,depot_walker_sameoutput,13.0,1,0,150,37,338, ,13,0.18000000000000002,0.01,36,2117.0,True,False,True,4,2,0
satellite_easy,p03-pfile3.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,11.0,1,0,46,11,229, ,11,0.03,0.01,42,2323.0,True,True,True,0,0,0
satellite_easy,p04-pfile4.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,23.0,1,0,106,26,544, ,23,0.04,0.01,50,3852.0,True,True,True,0,0,0
satellite_easy,p05-pfile5.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,22.0,1,0,166,41,1393, ,22,0.05,0.01,84,4365.0,True,True,True,0,0,0
satellite_easy,p06-pfile6.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,21.0,1,0,250,62,2158, ,21,0.05,0.01,73,4896.0,True,True,True,0,0,0
satellite_easy,p07-pfile7.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10668,depot_walker_sameoutput,23.0,1,0,94,23,1155, ,23,0.06999999999999999,0.01,102,6082.0,True,True,True,0,0,0
satellite_easy,p08-pfile8.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11044,depot_walker_sameoutput,29.0,1,0,134,33,2091, ,29,0.0909234,0.01,128,9317.0,True,True,True,0,0,0
satellite_easy,p09-pfile9.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11308,depot_walker_sameoutput,37.0,1,0,206,51,3920, ,37,0.1243151,0.01,149,9145.0,True,True,True,0,0,0
satellite_easy,p10-pfile10.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11596,depot_walker_sameoutput,35.0,1,0,238,59,5256, ,35,0.1373994,0.01,161,10915.0,True,True,True,0,0,0
satellite_easy,p11-pfile11.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12656,depot_walker_sameoutput,37.0,1,0,210,52,5290, ,37,0.1697615,0.0101539,168,12167.0,True,True,True,0,0,0
satellite_easy,p12-pfile12.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13860,depot_walker_sameoutput,43.0,1,0,202,50,6427, ,43,0.2478077,0.0105986,213,19774.0,True,True,True,0,0,0
satellite_easy,p13-pfile13.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16312,depot_walker_sameoutput,76.0,1,0,1198,299,45725, ,76,0.3971122,0.0648198,244,24695.0,True,True,True,0,0,0
satellite_easy,p14-pfile14.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14372,depot_walker_sameoutput,44.0,1,0,194,48,7444, ,44,0.31284560000000006,0.0144232,242,19194.0,True,True,True,0,0,0
satellite_easy,p15-pfile15.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15804,depot_walker_sameoutput,52.0,1,0,326,81,16849, ,52,0.4122921,0.0258612,328,23075.0,True,True,True,0,0,0
satellite_easy,p16-pfile16.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17040,depot_walker_sameoutput,56.0,1,0,418,104,27170, ,56,0.5086443,0.0353677,400,25268.0,True,True,True,0,0,0
satellite_easy,p17-pfile17.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17348,depot_walker_sameoutput,47.0,1,0,226,56,17365, ,47,0.37449360000000004,0.0119443,454,22199.0,True,True,True,0,0,0
satellite_easy,p18-pfile18.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13352,depot_walker_sameoutput,34.0,1,0,150,37,4724, ,34,0.245611,0.01,211,17102.0,True,True,True,0,0,0
satellite_easy,p19-pfile19.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15092,depot_walker_sameoutput,75.0,1,0,358,89,11447, ,75,0.20398739999999999,0.0119882,289,23030.0,True,True,True,0,0,0
satellite_easy,p20-pfile20.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17660,depot_walker_sameoutput,106.0,1,0,2274,568,74680, ,106,0.458164,0.11925,329,36716.0,True,True,True,0,0,0
zenotravel_easy,p01.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,1.0,1,0,10,2,7, ,1,0.04,0.01,29,12878.0,True,True,True,0,0,0
zenotravel_easy,p02.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,8.0,1,0,46,11,46, ,8,0.03,0.01,18,11578.0,True,True,True,0,0,0
zenotravel_easy,p03.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,6.0,1,0,66,16,265, ,6,0.04,0.01,40,25626.0,True,True,True,0,0,0
zenotravel_easy,p04.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,9.0,1,0,102,25,246, ,9,0.05,0.01,40,25078.0,True,True,True,0,0,0
zenotravel_easy,p05.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10532,depot_walker_sameoutput,12.0,1,0,154,38,462, ,12,0.060000000000000005,0.01,46,34902.0,True,True,True,0,0,0
zenotravel_easy,p06.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10532,depot_walker_sameoutput,14.0,1,0,130,32,469, ,14,0.05,0.01,52,38453.0,True,True,True,0,0,0
zenotravel_easy,p07.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10532,depot_walker_sameoutput,16.0,1,0,158,39,320, ,16,0.060000000000000005,0.01,52,35536.0,True,True,True,0,0,0
zenotravel_easy,p08.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11020,depot_walker_sameoutput,15.0,1,0,222,55,1296, ,15,0.11,0.01,84,55618.0,True,True,True,0,0,0
zenotravel_easy,p09.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11184,depot_walker_sameoutput,25.0,1,0,182,45,1011, ,25,0.1134961,0.01,92,60300.0,True,True,True,0,0,0
zenotravel_easy,p10.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11332,depot_walker_sameoutput,29.0,1,0,378,94,2274, ,29,0.1168035,0.01,100,58714.0,True,True,True,0,0,0
zenotravel_easy,p11.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11552,depot_walker_sameoutput,18.0,1,0,186,46,1776, ,18,0.1563585,0.01,102,75684.0,True,True,True,0,0,0
zenotravel_easy,p12.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11712,depot_walker_sameoutput,24.0,1,0,262,65,2003, ,24,0.139672,0.01,111,81694.0,True,True,True,0,0,0
zenotravel_easy,p13.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11732,depot_walker_sameoutput,32.0,1,0,514,128,4148, ,32,0.1748419,0.0132835,120,75787.0,True,True,True,0,0,0
zenotravel_easy,p14.pddl,regressor,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17404,depot_walker_sameoutput,37.0,1,0,606,151,13385, ,37,0.695505,0.0462113,220,162337.0,True,True,True,0,0,0
depot_easy,p01.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,10.0,1,0,86,21,132, ,10,0.04,0.01,48,145.0,True,True,True,0,0,0
depot_easy,p02.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10804,depot_walker_sameoutput,16.0,1,0,174,43,327, ,16,0.0513825,0.01,86,145.0,True,True,True,0,0,0
depot_easy,p03.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12256,depot_walker_sameoutput,51.0,1,0,1870,467,3706, ,51,0.14604460000000002,0.0655761,132,245.0,True,True,True,0,0,0
depot_easy,p04.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13968,depot_walker_sameoutput,57.0,1,0,3930,982,8832, ,57,0.330621,0.223893,186,506.0,True,True,True,0,0,0
depot_easy,p07.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12248,depot_walker_sameoutput,30.0,1,0,342,85,772, ,30,0.1179976,0.0149697,156,242.0,True,True,True,0,0,0
depot_easy,p08.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16008,depot_walker_sameoutput,45.0,1,0,1642,410,4761, ,45,0.354787,0.156569,284,536.0,True,True,True,0,0,0
depot_easy,p13.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15756,depot_walker_sameoutput,28.0,1,0,426,106,1612, ,28,0.2480646,0.037091,236,348.0,True,True,True,0,0,0
depot_easy,p14.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24056,depot_walker_sameoutput,49.0,1,0,726,181,3349, ,49,0.5678289999999999,0.147613,404,776.0,True,True,True,0,0,0
depot_easy,p16.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17604,depot_walker_sameoutput,34.0,1,0,718,179,4091, ,34,0.330324,0.0712672,240,495.0,True,True,True,0,0,0
depot_easy,p19.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,25716,depot_walker_sameoutput,56.0,1,0,1534,383,13526, ,56,0.825968,0.35596,388,1030.0,True,True,True,0,0,0
driverlog_easy,p01.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,8.0,1,0,38,9,61, ,8,0.02,0.01,34,115.0,True,True,True,0,0,0
driverlog_easy,p02.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11236,depot_walker_sameoutput,21.0,1,0,21838,5459,44791, ,21,0.1191934,0.095899,41,212.0,True,True,True,0,0,0
driverlog_easy,p03.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,15.0,1,0,130,32,226, ,15,0.03,0.01,41,140.0,True,True,True,0,0,0
driverlog_easy,p04.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11320,depot_walker_sameoutput,25.0,1,0,17982,4495,48198, ,25,0.1160704,0.0925515,51,219.0,True,True,True,0,0,0
driverlog_easy,p05.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,22.0,1,0,238,59,678, ,22,0.03,0.01,59,144.0,True,True,True,0,0,0
driverlog_easy,p06.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10540,depot_walker_sameoutput,15.0,1,0,2122,530,7060, ,15,0.0372135,0.0139709,69,294.0,True,True,True,0,0,0
driverlog_easy,p07.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,17.0,1,0,158,39,512, ,17,0.04,0.01,78,135.0,True,True,True,0,0,0
driverlog_easy,p08.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10800,depot_walker_sameoutput,27.0,1,0,4722,1180,19035, ,27,0.0663912,0.031892,84,180.0,True,True,True,0,0,0
driverlog_easy,p09.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11056,depot_walker_sameoutput,49.0,1,0,4850,1212,13521, ,49,0.08181240000000001,0.0372703,97,204.0,True,True,True,0,0,0
driverlog_easy,p10.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10668,depot_walker_sameoutput,21.0,1,0,262,65,891, ,21,0.060025800000000004,0.01,114,158.0,True,True,True,0,0,0
driverlog_easy,p11.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10800,depot_walker_sameoutput,27.0,1,0,358,89,1200, ,27,0.0730302,0.01,119,190.0,True,True,True,0,0,0
driverlog_easy,p12.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16080,depot_walker_sameoutput,41.0,1,0,49374,12343,167915, ,41,0.7426649999999999,0.654873,176,1078.0,True,True,True,0,0,0
driverlog_easy,p13.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12520,depot_walker_sameoutput,41.0,1,0,7590,1897,27491, ,41,0.230212,0.121138,197,321.0,True,True,True,0,0,0
driverlog_easy,p14.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13308,depot_walker_sameoutput,56.0,1,0,13718,3429,56204, ,56,0.36731199999999997,0.248225,195,472.0,True,True,True,0,0,0
driverlog_easy,p15.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14012,depot_walker_sameoutput,53.0,1,0,926,231,4235, ,53,0.2754841,0.0479242,336,384.0,True,True,True,0,0,0
driverlog_easy,p17.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22952,depot_walker_sameoutput,123.0,1,0,4714,1178,37225, ,123,1.0108030000000001,0.511937,665,1254.0,True,True,True,0,0,0
freecell_easy,p01.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12004,depot_walker_sameoutput,8.0,1,0,34,8,46, ,8,0.1054563,0.01,75,220.0,True,True,True,0,0,0
freecell_easy,p02.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14756,depot_walker_sameoutput,15.0,1,0,62,15,99, ,15,0.20339310000000002,0.01,112,314.0,True,True,True,0,0,0
freecell_easy,p03.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16180,depot_walker_sameoutput,20.0,1,0,86,21,156, ,20,0.2883888,0.0145715,146,469.0,True,True,True,0,0,0
freecell_easy,p04.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19252,depot_walker_sameoutput,29.0,1,0,334,83,498, ,29,0.403848,0.0604128,180,555.0,True,True,True,0,0,0
freecell_easy,p05.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22792,depot_walker_sameoutput,34.0,1,0,186,46,277, ,34,0.577794,0.0503017,220,750.0,True,True,True,0,0,0
freecell_easy,p06.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,33524,depot_walker_sameoutput,40.0,1,3,405,100,744, ,40,0.9073180000000001,0.151248,255,1198.0,True,True,True,0,0,0
freecell_easy,p07.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,34188,depot_walker_sameoutput,53.0,1,3,1137,283,1437, ,53,1.2019700000000002,0.422489,259,1434.0,True,True,True,0,0,0
freecell_easy,probfreecell-2-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23428,depot_walker_sameoutput,9.0,1,0,38,9,54, ,9,0.5565015999999999,0.0126963,92,672.0,True,True,True,0,0,0
freecell_easy,probfreecell-2-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22932,depot_walker_sameoutput,8.0,1,0,34,8,68, ,8,0.5229961,0.01,91,670.0,True,True,True,0,0,0
freecell_easy,probfreecell-2-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23360,depot_walker_sameoutput,8.0,1,0,34,8,50, ,8,0.5775238,0.0114672,92,779.0,True,True,True,0,0,0
freecell_easy,probfreecell-2-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23192,depot_walker_sameoutput,8.0,1,0,34,8,68, ,8,0.544444,0.0118791,90,713.0,True,True,True,0,0,0
freecell_easy,probfreecell-2-5.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23580,depot_walker_sameoutput,9.0,1,0,38,9,61, ,9,0.5570406999999999,0.0117081,92,732.0,True,True,True,0,0,0
freecell_easy,probfreecell-3-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,34468,depot_walker_sameoutput,14.0,1,0,58,14,111, ,14,0.887513,0.0301429,125,1094.0,True,True,True,0,0,0
freecell_easy,probfreecell-3-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,33952,depot_walker_sameoutput,13.0,1,0,54,13,133, ,13,0.903244,0.0264355,124,1200.0,True,True,True,0,0,0
freecell_easy,probfreecell-3-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,33864,depot_walker_sameoutput,13.0,1,0,54,13,132, ,13,0.930453,0.0277015,126,1230.0,True,True,True,0,0,0
freecell_easy,probfreecell-3-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,33356,depot_walker_sameoutput,12.0,1,0,50,12,138, ,12,0.890933,0.0242477,125,1063.0,True,True,True,0,0,0
freecell_easy,probfreecell-3-5.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,34412,depot_walker_sameoutput,14.0,1,0,58,14,134, ,14,0.924972,0.0285946,124,1218.0,True,True,True,0,0,0
gripper,prob01.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,13.0,1,0,74,18,75, ,13,0.02,0.01,24,101.0,True,True,True,0,0,0
gripper,prob02.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10276,depot_walker_sameoutput,21.0,1,0,114,28,151, ,21,0.02,0.01,34,95.0,True,True,True,0,0,0
gripper,prob03.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,29.0,1,0,154,38,251, ,29,0.02,0.01,44,123.0,True,True,True,0,0,0
gripper,prob04.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,37.0,1,0,194,48,375, ,37,0.02,0.01,54,105.0,True,True,True,0,0,0
gripper,prob05.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10540,depot_walker_sameoutput,45.0,1,0,234,58,523, ,45,0.02,0.01,64,123.0,True,True,True,0,0,0
gripper,prob06.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10664,depot_walker_sameoutput,53.0,1,0,274,68,695, ,53,0.02,0.01,74,134.0,True,True,True,0,0,0
gripper,prob07.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10792,depot_walker_sameoutput,61.0,1,0,314,78,891, ,61,0.0405196,0.01,84,114.0,True,True,True,0,0,0
gripper,prob08.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11040,depot_walker_sameoutput,69.0,1,0,354,88,1111, ,69,0.0315054,0.01,94,172.0,True,True,True,0,0,0
gripper,prob09.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11180,depot_walker_sameoutput,77.0,1,0,394,98,1355, ,77,0.0429412,0.01,104,135.0,True,True,True,0,0,0
gripper,prob10.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11444,depot_walker_sameoutput,85.0,1,0,434,108,1623, ,85,0.0333493,0.01,114,123.0,True,True,True,0,0,0
gripper,prob11.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11568,depot_walker_sameoutput,93.0,1,0,474,118,1915, ,93,0.046440499999999996,0.0131192,124,127.0,True,True,True,0,0,0
gripper,prob12.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11824,depot_walker_sameoutput,101.0,1,0,514,128,2231, ,101,0.0482278,0.0132783,134,159.0,True,True,True,0,0,0
gripper,prob13.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11960,depot_walker_sameoutput,109.0,1,0,554,138,2571, ,109,0.049927799999999994,0.0157427,144,161.0,True,True,True,0,0,0
gripper,prob14.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12240,depot_walker_sameoutput,117.0,1,0,594,148,2935, ,117,0.0516368,0.0163731,154,172.0,True,True,True,0,0,0
gripper,prob15.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12548,depot_walker_sameoutput,125.0,1,0,634,158,3323, ,125,0.0645731,0.0189934,164,150.0,True,True,True,0,0,0
gripper,prob16.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13144,depot_walker_sameoutput,133.0,1,0,674,168,3735, ,133,0.0653304,0.0200785,174,152.0,True,True,True,0,0,0
gripper,prob17.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13528,depot_walker_sameoutput,141.0,1,0,714,178,4171, ,141,0.0686165,0.0229044,184,181.0,True,True,True,0,0,0
gripper,prob18.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13772,depot_walker_sameoutput,149.0,1,0,754,188,4631, ,149,0.0707409,0.0250718,194,167.0,True,True,True,0,0,0
gripper,prob19.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14024,depot_walker_sameoutput,157.0,1,0,794,198,5115, ,157,0.0632604,0.0272941,204,187.0,True,True,True,0,0,0
gripper,prob20.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14348,depot_walker_sameoutput,165.0,1,0,834,208,5623, ,165,0.0844183,0.0282016,214,162.0,True,True,True,0,0,0
hanoi,pb1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10276,depot_walker_sameoutput,7.0,1,0,70,17,49, ,7,0.02,0.01,22,120.0,True,True,True,0,0,0
hanoi,pb2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10408,depot_walker_sameoutput,15.0,1,0,150,37,110, ,15,0.02,0.01,30,110.0,True,True,True,0,0,0
hanoi,pb3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,38.0,1,0,922,230,688, ,38,0.0200246,0.01,39,127.0,True,True,True,0,0,0
hanoi,pb4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,70.0,1,0,1446,361,1082, ,70,0.0366871,0.0144342,49,120.0,True,True,True,0,0,0
hanoi,pb5.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10812,depot_walker_sameoutput,164.0,1,0,4362,1090,3269, ,164,0.087678,0.0514052,60,219.0,True,True,True,0,0,0
hanoi,pb6.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11352,depot_walker_sameoutput,314.0,1,0,12278,3069,9206, ,314,0.240589,0.204367,72,360.0,True,True,True,0,0,0
logistics_easy,p01.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14240,depot_walker_sameoutput,32.0,1,0,430,107,16192, ,32,0.2625757,0.0259259,559,373.0,True,True,True,0,0,0
logistics_easy,p02.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19132,depot_walker_sameoutput,53.0,1,0,1618,404,79921, ,53,0.598076,0.152484,1206,1060.0,True,True,True,0,0,0
logistics_easy,p03.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,26572,depot_walker_sameoutput,81.0,1,0,2754,688,179477, ,81,1.2162739999999999,0.428185,2175,1460.0,True,True,True,0,0,0
miconic,s1-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,4.0,1,0,18,4,7, ,4,0.02,0.01,6,85.0,True,True,True,0,0,0
miconic,s1-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,3.0,1,0,14,3,6, ,3,0.01,0.01,6,117.0,True,True,True,0,0,0
miconic,s1-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,4.0,1,0,18,4,7, ,4,0.02,0.01,6,111.0,True,True,True,0,0,0
miconic,s1-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,4.0,1,0,18,4,7, ,4,0.02,0.01,6,115.0,True,True,True,0,0,0
miconic,s1-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,4.0,1,0,18,4,7, ,4,0.02,0.01,6,106.0,True,True,True,0,0,0
miconic,s10-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11168,depot_walker_sameoutput,47.0,1,0,574,143,2833, ,47,0.040604,0.0102622,60,131.0,True,True,True,0,0,0
miconic,s10-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11044,depot_walker_sameoutput,41.0,1,0,462,115,2296, ,41,0.0412863,0.01,60,158.0,True,True,True,0,0,0
miconic,s10-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11044,depot_walker_sameoutput,45.0,1,0,518,129,2593, ,45,0.04,0.01,60,134.0,True,True,True,0,0,0
miconic,s10-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11312,depot_walker_sameoutput,38.0,1,0,450,112,2249, ,38,0.0407245,0.01,60,127.0,True,True,True,0,0,0
miconic,s10-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11036,depot_walker_sameoutput,43.0,1,0,474,118,2352, ,43,0.0501708,0.01,60,134.0,True,True,True,0,0,0
miconic,s11-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11328,depot_walker_sameoutput,54.0,1,0,758,189,4156, ,54,0.044355,0.0101589,66,162.0,True,True,True,0,0,0
miconic,s11-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11196,depot_walker_sameoutput,49.0,1,0,546,136,3016, ,49,0.0417211,0.01,66,148.0,True,True,True,0,0,0
miconic,s11-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11464,depot_walker_sameoutput,57.0,1,0,858,214,4657, ,57,0.0662397,0.0119668,66,161.0,True,True,True,0,0,0
miconic,s11-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11460,depot_walker_sameoutput,47.0,1,0,606,151,3305, ,47,0.0530959,0.01,66,164.0,True,True,True,0,0,0
miconic,s11-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11332,depot_walker_sameoutput,46.0,1,0,718,179,3954, ,46,0.043257199999999996,0.01,66,160.0,True,True,True,0,0,0
miconic,s12-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11724,depot_walker_sameoutput,48.0,1,0,554,138,3317, ,48,0.05,0.01,72,144.0,True,True,True,0,0,0
miconic,s12-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11596,depot_walker_sameoutput,54.0,1,0,706,176,4232, ,54,0.0557775,0.010749,72,148.0,True,True,True,0,0,0
miconic,s12-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11592,depot_walker_sameoutput,57.0,1,0,846,211,5045, ,57,0.067666,0.0122777,72,178.0,True,True,True,0,0,0
miconic,s12-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11460,depot_walker_sameoutput,54.0,1,0,738,184,4411, ,54,0.06543020000000001,0.0110627,72,154.0,True,True,True,0,0,0
miconic,s12-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11724,depot_walker_sameoutput,61.0,1,0,966,241,5728, ,61,0.057747599999999996,0.0128561,72,168.0,True,True,True,0,0,0
miconic,s13-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11852,depot_walker_sameoutput,55.0,1,0,846,211,5490, ,55,0.0682982,0.0136227,78,180.0,True,True,True,0,0,0
miconic,s13-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11720,depot_walker_sameoutput,59.0,1,0,910,227,5901, ,59,0.0683063,0.0138539,78,177.0,True,True,True,0,0,0
miconic,s13-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12120,depot_walker_sameoutput,64.0,1,0,934,233,6007, ,64,0.0701691,0.014704,78,204.0,True,True,True,0,0,0
miconic,s13-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11852,depot_walker_sameoutput,56.0,1,0,674,168,4365, ,56,0.0676405,0.0118788,78,172.0,True,True,True,0,0,0
miconic,s13-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11720,depot_walker_sameoutput,53.0,1,0,838,209,5457, ,53,0.06784480000000001,0.0125705,78,165.0,True,True,True,0,0,0
miconic,s14-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12008,depot_walker_sameoutput,55.0,1,0,810,202,5634, ,55,0.0791514,0.0140286,84,197.0,True,True,True,0,0,0
miconic,s14-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12268,depot_walker_sameoutput,68.0,1,0,1034,258,7223, ,68,0.0926821,0.0174197,84,177.0,True,True,True,0,0,0
miconic,s14-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12396,depot_walker_sameoutput,67.0,1,0,1094,273,7611, ,67,0.0828797,0.0176603,84,174.0,True,True,True,0,0,0
miconic,s14-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11752,depot_walker_sameoutput,55.0,1,0,762,190,5379, ,55,0.0768926,0.011988,84,236.0,True,True,True,0,0,0
miconic,s14-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12124,depot_walker_sameoutput,65.0,1,0,878,219,6135, ,65,0.0812644,0.0154246,84,202.0,True,True,True,0,0,0
miconic,s15-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12232,depot_walker_sameoutput,61.0,1,0,962,240,7231, ,61,0.08318529999999999,0.0169132,90,197.0,True,True,True,0,0,0
miconic,s15-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13140,depot_walker_sameoutput,75.0,1,0,1426,356,10622, ,75,0.08981539999999999,0.0244923,90,258.0,True,True,True,0,0,0
miconic,s15-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12900,depot_walker_sameoutput,69.0,1,0,1214,303,9059, ,69,0.0972704,0.0209447,90,183.0,True,True,True,0,0,0
miconic,s15-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12616,depot_walker_sameoutput,68.0,1,0,1182,295,8820, ,68,0.09679070000000001,0.0209034,90,265.0,True,True,True,0,0,0
miconic,s15-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12232,depot_walker_sameoutput,69.0,1,0,1042,260,7825, ,69,0.08426,0.0183003,90,182.0,True,True,True,0,0,0
miconic,s16-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12912,depot_walker_sameoutput,74.0,1,0,1382,345,11005, ,74,0.1125048,0.025325,96,274.0,True,True,True,0,0,0
miconic,s16-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12780,depot_walker_sameoutput,68.0,1,0,1062,265,8480, ,68,0.0957019,0.0199382,96,193.0,True,True,True,0,0,0
miconic,s16-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12904,depot_walker_sameoutput,76.0,1,0,1382,345,10992, ,76,0.10080810000000001,0.0248422,96,196.0,True,True,True,0,0,0
miconic,s16-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12640,depot_walker_sameoutput,69.0,1,0,1226,306,9850, ,69,0.10971790000000001,0.0229963,96,206.0,True,True,True,0,0,0
miconic,s16-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12780,depot_walker_sameoutput,72.0,1,0,1194,298,9532, ,72,0.1091549,0.0224065,96,193.0,True,True,True,0,0,0
miconic,s17-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15144,depot_walker_sameoutput,76.0,1,0,1758,439,14920, ,76,0.1200144,0.0350904,102,240.0,True,True,True,0,0,0
miconic,s17-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14884,depot_walker_sameoutput,77.0,1,0,1390,347,11820, ,77,0.1134443,0.0264816,102,206.0,True,True,True,0,0,0
miconic,s17-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14880,depot_walker_sameoutput,78.0,1,0,1470,367,12508, ,78,0.1146746,0.0283282,102,207.0,True,True,True,0,0,0
miconic,s17-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15800,depot_walker_sameoutput,84.0,1,0,1718,429,14511, ,84,0.1193168,0.0330473,102,211.0,True,True,True,0,0,0
miconic,s17-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14864,depot_walker_sameoutput,68.0,1,0,1230,307,10483, ,68,0.1124472,0.0256112,102,249.0,True,True,True,0,0,0
miconic,s18-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15812,depot_walker_sameoutput,80.0,1,0,1506,376,13541, ,80,0.1316545,0.034592,108,296.0,True,True,True,0,0,0
miconic,s18-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15540,depot_walker_sameoutput,78.0,1,0,1406,351,12684, ,78,0.1384948,0.0305339,108,250.0,True,True,True,0,0,0
miconic,s18-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15540,depot_walker_sameoutput,83.0,1,0,1562,390,14059, ,83,0.1524096,0.0342699,108,231.0,True,True,True,0,0,0
miconic,s18-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16044,depot_walker_sameoutput,83.0,1,0,1686,421,15115, ,83,0.1313597,0.0345487,108,310.0,True,True,True,0,0,0
miconic,s18-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15140,depot_walker_sameoutput,84.0,1,0,1674,418,15033, ,84,0.1226957,0.0349558,108,263.0,True,True,True,0,0,0
miconic,s19-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16412,depot_walker_sameoutput,83.0,1,0,1730,432,16460, ,83,0.1476743,0.0390561,114,292.0,True,True,True,0,0,0
miconic,s19-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17080,depot_walker_sameoutput,80.0,1,0,1626,406,15396, ,80,0.1435799,0.0359517,114,245.0,True,True,True,0,0,0
miconic,s19-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16408,depot_walker_sameoutput,94.0,1,0,1938,484,18349, ,94,0.158985,0.044049,114,294.0,True,True,True,0,0,0
miconic,s19-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16676,depot_walker_sameoutput,91.0,1,0,1974,493,18766, ,91,0.157137,0.0490511,114,387.0,True,True,True,0,0,0
miconic,s19-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16400,depot_walker_sameoutput,86.0,1,0,1774,443,16838, ,86,0.1465922,0.0390877,114,256.0,True,True,True,0,0,0
miconic,s2-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,8.0,1,0,38,9,36, ,8,0.01,0.01,12,90.0,True,True,True,0,0,0
miconic,s2-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,8.0,1,0,38,9,36, ,8,0.02,0.01,12,84.0,True,True,True,0,0,0
miconic,s2-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,8.0,1,0,38,9,36, ,8,0.01,0.01,12,94.0,True,True,True,0,0,0
miconic,s2-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,7.0,1,0,30,7,28, ,7,0.02,0.01,12,105.0,True,True,True,0,0,0
miconic,s2-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,9.0,1,0,46,11,42, ,9,0.01,0.01,12,88.0,True,True,True,0,0,0
miconic,s20-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16748,depot_walker_sameoutput,86.0,1,0,1766,441,17653, ,86,0.16098099999999999,0.0420232,120,315.0,True,True,True,0,0,0
miconic,s20-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17280,depot_walker_sameoutput,95.0,1,0,2082,520,20745, ,95,0.166763,0.0478432,120,304.0,True,True,True,0,0,0
miconic,s20-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16340,depot_walker_sameoutput,89.0,1,0,1826,456,18294, ,89,0.1713265,0.0423325,120,274.0,True,True,True,0,0,0
miconic,s20-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16480,depot_walker_sameoutput,95.0,1,0,1818,454,18296, ,95,0.1623189,0.0437925,120,289.0,True,True,True,0,0,0
miconic,s20-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16744,depot_walker_sameoutput,85.0,1,0,1830,457,18323, ,85,0.1722036,0.0438524,120,257.0,True,True,True,0,0,0
miconic,s21-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17864,depot_walker_sameoutput,103.0,1,0,2098,524,21943, ,103,0.1912607,0.0514917,126,281.0,True,True,True,0,0,0
miconic,s21-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17884,depot_walker_sameoutput,100.0,1,0,2302,575,24222, ,100,0.2065401,0.0574479,126,325.0,True,True,True,0,0,0
miconic,s21-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17764,depot_walker_sameoutput,96.0,1,0,1730,432,18161, ,96,0.17437419999999998,0.0444269,126,303.0,True,True,True,0,0,0
miconic,s21-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17216,depot_walker_sameoutput,92.0,1,0,2154,538,22548, ,92,0.1816455,0.052891,126,369.0,True,True,True,0,0,0
miconic,s21-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18016,depot_walker_sameoutput,92.0,1,0,1782,445,18726, ,92,0.1861737,0.0469056,126,345.0,True,True,True,0,0,0
miconic,s22-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18756,depot_walker_sameoutput,109.0,1,0,2902,725,31850, ,109,0.2277226,0.0774912,132,364.0,True,True,True,0,0,0
miconic,s22-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18084,depot_walker_sameoutput,104.0,1,0,2406,601,26438, ,104,0.2022495,0.0625336,132,308.0,True,True,True,0,0,0
miconic,s22-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18360,depot_walker_sameoutput,102.0,1,0,2594,648,28517, ,102,0.2262979,0.0660192,132,412.0,True,True,True,0,0,0
miconic,s22-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19440,depot_walker_sameoutput,102.0,1,0,2818,704,30893, ,102,0.2248381,0.0759351,132,375.0,True,True,True,0,0,0
miconic,s22-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19024,depot_walker_sameoutput,101.0,1,0,2362,590,25971, ,101,0.2035132,0.0629624,132,360.0,True,True,True,0,0,0
miconic,s23-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19372,depot_walker_sameoutput,110.0,1,0,2858,714,32841, ,110,0.24126140000000001,0.0799858,138,343.0,True,True,True,0,0,0
miconic,s23-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19104,depot_walker_sameoutput,105.0,1,0,2698,674,30995, ,105,0.2440443,0.0729301,138,334.0,True,True,True,0,0,0
miconic,s23-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18600,depot_walker_sameoutput,89.0,1,0,1942,485,22475, ,89,0.2151139,0.0548093,138,331.0,True,True,True,0,0,0
miconic,s23-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18460,depot_walker_sameoutput,100.0,1,0,2458,614,28373, ,100,0.2183363,0.0670414,138,325.0,True,True,True,0,0,0
miconic,s23-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19252,depot_walker_sameoutput,107.0,1,0,2506,626,28784, ,107,0.2322809,0.0720731,138,338.0,True,True,True,0,0,0
miconic,s24-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19976,depot_walker_sameoutput,97.0,1,0,1854,463,22230, ,97,0.2410498,0.0584776,144,363.0,True,True,True,0,0,0
miconic,s24-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20008,depot_walker_sameoutput,118.0,1,0,2814,703,33799, ,118,0.251927,0.0802842,144,372.0,True,True,True,0,0,0
miconic,s24-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20948,depot_walker_sameoutput,113.0,1,0,3238,809,38776, ,113,0.255803,0.0950093,144,431.0,True,True,True,0,0,0
miconic,s24-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20396,depot_walker_sameoutput,112.0,1,0,2946,736,35321, ,112,0.2859869,0.084133,144,376.0,True,True,True,0,0,0
miconic,s24-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19996,depot_walker_sameoutput,115.0,1,0,3262,815,39113, ,115,0.279,0.0974004,144,422.0,True,True,True,0,0,0
miconic,s25-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20944,depot_walker_sameoutput,110.0,1,0,2502,625,31260, ,110,0.2807172,0.078098,150,405.0,True,True,True,0,0,0
miconic,s25-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22080,depot_walker_sameoutput,128.0,1,0,3670,917,45740, ,128,0.30810899999999997,0.116469,150,432.0,True,True,True,0,0,0
miconic,s25-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20036,depot_walker_sameoutput,111.0,1,0,2870,717,36023, ,111,0.29116600000000004,0.0894352,150,479.0,True,True,True,0,0,0
miconic,s25-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,21740,depot_walker_sameoutput,118.0,1,0,3250,812,40469, ,118,0.289465,0.0978646,150,408.0,True,True,True,0,0,0
miconic,s25-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,21228,depot_walker_sameoutput,124.0,1,0,3338,834,41667, ,124,0.30756700000000003,0.105921,150,504.0,True,True,True,0,0,0
miconic,s26-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,21392,depot_walker_sameoutput,128.0,1,0,3370,842,43724, ,128,0.338459,0.1249,156,507.0,True,True,True,0,0,0
miconic,s26-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,21400,depot_walker_sameoutput,117.0,1,0,3302,825,42998, ,117,0.323181,0.109599,156,459.0,True,True,True,0,0,0
miconic,s26-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23784,depot_walker_sameoutput,130.0,1,0,3670,917,47573, ,130,0.32723199999999997,0.124832,156,512.0,True,True,True,0,0,0
miconic,s26-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22892,depot_walker_sameoutput,127.0,1,0,3774,943,48970, ,127,0.347329,0.124474,156,634.0,True,True,True,0,0,0
miconic,s26-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20880,depot_walker_sameoutput,113.0,1,0,2586,646,33670, ,113,0.2969569,0.0835053,156,402.0,True,True,True,0,0,0
miconic,s27-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24268,depot_walker_sameoutput,138.0,1,0,4518,1129,60944, ,138,0.3735,0.159757,162,492.0,True,True,True,0,0,0
miconic,s27-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23732,depot_walker_sameoutput,124.0,1,0,3818,954,51488, ,124,0.369723,0.135806,162,548.0,True,True,True,0,0,0
miconic,s27-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22824,depot_walker_sameoutput,136.0,1,0,4322,1080,58279, ,136,0.399357,0.154737,162,527.0,True,True,True,0,0,0
miconic,s27-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23192,depot_walker_sameoutput,132.0,1,0,3742,935,50427, ,132,0.35480999999999996,0.130339,162,507.0,True,True,True,0,0,0
miconic,s27-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22972,depot_walker_sameoutput,120.0,1,0,3950,987,53359, ,120,0.36074,0.136827,162,513.0,True,True,True,0,0,0
miconic,s28-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,25012,depot_walker_sameoutput,138.0,1,0,4786,1196,66750, ,138,0.426589,0.181336,168,564.0,True,True,True,0,0,0
miconic,s28-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23984,depot_walker_sameoutput,127.0,1,0,3602,900,50486, ,127,0.39413,0.149002,168,505.0,True,True,True,0,0,0
miconic,s28-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24508,depot_walker_sameoutput,138.0,1,0,4254,1063,59504, ,138,0.395428,0.160541,168,573.0,True,True,True,0,0,0
miconic,s28-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22116,depot_walker_sameoutput,121.0,1,0,2834,708,39852, ,121,0.33423800000000004,0.0993776,168,475.0,True,True,True,0,0,0
miconic,s28-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24236,depot_walker_sameoutput,130.0,1,0,3658,914,51174, ,130,0.38253,0.12777,168,509.0,True,True,True,0,0,0
miconic,s29-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24720,depot_walker_sameoutput,135.0,1,0,4218,1054,61165, ,135,0.422721,0.167111,174,622.0,True,True,True,0,0,0
miconic,s29-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23812,depot_walker_sameoutput,133.0,1,0,4206,1051,61114, ,133,0.41137900000000005,0.1653,174,558.0,True,True,True,0,0,0
miconic,s29-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,25140,depot_walker_sameoutput,131.0,1,0,3790,947,55011, ,131,0.409501,0.143111,174,495.0,True,True,True,0,0,0
miconic,s29-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,25416,depot_walker_sameoutput,145.0,1,0,4566,1141,66072, ,145,0.429775,0.174057,174,651.0,True,True,True,0,0,0
miconic,s29-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,26476,depot_walker_sameoutput,147.0,1,0,4830,1207,69751, ,147,0.457317,0.193955,174,637.0,True,True,True,0,0,0
miconic,s3-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10276,depot_walker_sameoutput,13.0,1,0,74,18,108, ,13,0.02,0.01,18,92.0,True,True,True,0,0,0
miconic,s3-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10276,depot_walker_sameoutput,14.0,1,0,82,20,118, ,14,0.02,0.01,18,207.0,True,True,True,0,0,0
miconic,s3-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10276,depot_walker_sameoutput,12.0,1,0,78,19,110, ,12,0.01,0.01,18,135.0,True,True,True,0,0,0
miconic,s3-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10276,depot_walker_sameoutput,10.0,1,0,70,17,103, ,10,0.02,0.01,18,87.0,True,True,True,0,0,0
miconic,s3-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10276,depot_walker_sameoutput,11.0,1,0,70,17,104, ,11,0.02,0.01,18,90.0,True,True,True,0,0,0
miconic,s30-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,24740,depot_walker_sameoutput,133.0,1,0,3662,915,54891, ,133,0.436794,0.153121,180,529.0,True,True,True,0,0,0
miconic,s30-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,25892,depot_walker_sameoutput,140.0,1,0,4294,1073,64408, ,140,0.436018,0.169953,180,555.0,True,True,True,0,0,0
miconic,s30-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,26580,depot_walker_sameoutput,129.0,1,0,3738,934,56218, ,129,0.427869,0.15093,180,562.0,True,True,True,0,0,0
miconic,s30-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,27092,depot_walker_sameoutput,142.0,1,0,4862,1215,72753, ,142,0.470312,0.203325,180,625.0,True,True,True,0,0,0
miconic,s30-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,26452,depot_walker_sameoutput,143.0,1,0,4794,1198,71803, ,143,0.46462899999999996,0.19792,180,623.0,True,True,True,0,0,0
miconic,s4-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,15.0,1,0,94,23,185, ,15,0.03,0.01,24,132.0,True,True,True,0,0,0
miconic,s4-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,14.0,1,0,90,22,178, ,14,0.02,0.01,24,234.0,True,True,True,0,0,0
miconic,s4-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,18.0,1,0,166,41,322, ,18,0.01,0.01,24,93.0,True,True,True,0,0,0
miconic,s4-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,19.0,1,0,154,38,297, ,19,0.02,0.01,24,106.0,True,True,True,0,0,0
miconic,s4-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,21.0,1,0,150,37,286, ,21,0.02,0.01,24,108.0,True,True,True,0,0,0
miconic,s5-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,24.0,1,0,170,42,408, ,24,0.03,0.01,30,103.0,True,True,True,0,0,0
miconic,s5-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,20.0,1,0,198,49,480, ,20,0.02,0.01,30,170.0,True,True,True,0,0,0
miconic,s5-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,20.0,1,0,138,34,350, ,20,0.03,0.01,30,153.0,True,True,True,0,0,0
miconic,s5-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,21.0,1,0,154,38,379, ,21,0.02,0.01,30,109.0,True,True,True,0,0,0
miconic,s5-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,24.0,1,0,174,43,421, ,24,0.03,0.01,30,98.0,True,True,True,0,0,0
miconic,s6-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,21.0,1,0,198,49,598, ,21,0.02,0.01,36,111.0,True,True,True,0,0,0
miconic,s6-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,23.0,1,0,158,39,473, ,23,0.02,0.01,36,160.0,True,True,True,0,0,0
miconic,s6-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,25.0,1,0,230,57,679, ,25,0.02,0.01,36,115.0,True,True,True,0,0,0
miconic,s6-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,22.0,1,0,202,50,602, ,22,0.02,0.01,36,131.0,True,True,True,0,0,0
miconic,s6-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,24.0,1,0,230,57,682, ,24,0.02,0.01,36,115.0,True,True,True,0,0,0
miconic,s7-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,29.0,1,0,214,53,740, ,29,0.04,0.01,42,115.0,True,True,True,0,0,0
miconic,s7-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,34.0,1,0,354,88,1214, ,34,0.03,0.01,42,127.0,True,True,True,0,0,0
miconic,s7-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,23.0,1,0,190,47,675, ,23,0.03,0.01,42,151.0,True,True,True,0,0,0
miconic,s7-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,28.0,1,0,254,63,880, ,28,0.03,0.01,42,144.0,True,True,True,0,0,0
miconic,s7-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,35.0,1,0,358,89,1215, ,35,0.02,0.01,42,181.0,True,True,True,0,0,0
miconic,s8-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,34.0,1,0,282,70,1114, ,34,0.04,0.01,48,124.0,True,True,True,0,0,0
miconic,s8-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,33.0,1,0,334,83,1343, ,33,0.03,0.01,48,239.0,True,True,True,0,0,0
miconic,s8-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,34.0,1,0,358,89,1417, ,34,0.03,0.01,48,131.0,True,True,True,0,0,0
miconic,s8-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,37.0,1,0,418,104,1657, ,37,0.03,0.01,48,132.0,True,True,True,0,0,0
miconic,s8-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10540,depot_walker_sameoutput,30.0,1,0,330,82,1315, ,30,0.05,0.01,48,176.0,True,True,True,0,0,0
miconic,s9-0.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10932,depot_walker_sameoutput,43.0,1,0,478,119,2114, ,43,0.04,0.01,54,142.0,True,True,True,0,0,0
miconic,s9-1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10932,depot_walker_sameoutput,42.0,1,0,466,116,2090, ,42,0.04,0.01,54,122.0,True,True,True,0,0,0
miconic,s9-2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10932,depot_walker_sameoutput,40.0,1,0,518,129,2319, ,40,0.0301407,0.01,54,122.0,True,True,True,0,0,0
miconic,s9-3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11064,depot_walker_sameoutput,35.0,1,0,378,94,1689, ,35,0.03,0.01,54,119.0,True,True,True,0,0,0
miconic,s9-4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10800,depot_walker_sameoutput,33.0,1,0,358,89,1627, ,33,0.04,0.01,54,125.0,True,True,True,0,0,0
mprime_easy,prob01.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11860,depot_walker_sameoutput,5.0,1,0,30,7,169, ,5,0.1330773,0.01,73,227.0,True,True,True,0,0,0
mprime_easy,prob02.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17928,depot_walker_sameoutput,10.0,1,0,62,15,847, ,10,0.47685109999999997,0.0114133,299,643.0,True,True,True,0,0,0
mprime_easy,prob03.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15508,depot_walker_sameoutput,4.0,1,0,34,8,589, ,4,0.3453427,0.01,231,472.0,True,True,True,0,0,0
mprime_easy,prob04.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12168,depot_walker_sameoutput,8.0,1,0,42,10,408, ,8,0.1363719,0.01,139,234.0,True,True,True,0,0,0
mprime_easy,prob05.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16416,depot_walker_sameoutput,12.0,1,0,78,19,496, ,12,0.398625,0.0119112,260,545.0,True,True,True,0,0,0
mprime_easy,prob07.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12928,depot_walker_sameoutput,5.0,1,0,38,9,256, ,5,0.2010464,0.01,352,302.0,True,True,True,0,0,0
mprime_easy,prob09.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15332,depot_walker_sameoutput,8.0,1,0,82,20,694, ,8,0.3297593,0.0100167,222,444.0,True,True,True,0,0,0
mprime_easy,prob11.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12488,depot_walker_sameoutput,7.0,1,0,62,15,522, ,7,0.166856,0.01,131,272.0,True,True,True,0,0,0
mprime_easy,prob12.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14848,depot_walker_sameoutput,6.0,1,0,42,10,333, ,6,0.2688197,0.01,136,361.0,True,True,True,0,0,0
mprime_easy,prob16.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,23732,depot_walker_sameoutput,6.0,1,0,42,10,752, ,6,0.8724287000000001,0.015851,333,1159.0,True,True,True,0,0,0
mprime_easy,prob25.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10812,depot_walker_sameoutput,4.0,1,0,26,6,77, ,4,0.060000000000000005,0.01,52,197.0,True,True,True,0,0,0
mprime_easy,prob26.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,18760,depot_walker_sameoutput,6.0,1,0,38,9,641, ,6,0.5346808,0.01,220,696.0,True,True,True,0,0,0
mprime_easy,prob27.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,26820,depot_walker_sameoutput,5.0,1,0,38,9,426, ,5,0.7207115000000001,0.01,184,863.0,True,True,True,0,0,0
mprime_easy,prob28.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12256,depot_walker_sameoutput,11.0,1,0,70,17,308, ,11,0.1257801,0.01,90,214.0,True,True,True,0,0,0
mprime_easy,prob29.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17784,depot_walker_sameoutput,4.0,1,0,30,7,358, ,4,0.4755951,0.01,206,651.0,True,True,True,0,0,0
mprime_easy,prob31.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,20752,depot_walker_sameoutput,4.0,1,0,22,5,175, ,4,0.6590465,0.01,343,811.0,True,True,True,0,0,0
mprime_easy,prob32.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13760,depot_walker_sameoutput,7.0,1,0,54,13,349, ,7,0.2152161,0.01,214,304.0,True,True,True,0,0,0
mprime_easy,prob34.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19948,depot_walker_sameoutput,4.0,1,0,30,7,234, ,4,0.6575499,0.01,370,778.0,True,True,True,0,0,0
mprime_easy,prob35.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12136,depot_walker_sameoutput,5.0,1,0,34,8,160, ,5,0.1248326,0.01,96,231.0,True,True,True,0,0,0
mystery_easy,prob01.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,5.0,1,0,30,7,22, ,5,0.03,0.01,58,128.0,True,True,True,0,0,0
mystery_easy,prob02.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17016,depot_walker_sameoutput,8.0,1,0,70,17,353, ,8,0.4204407,0.010941,292,541.0,True,True,True,0,0,0
mystery_easy,prob03.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13228,depot_walker_sameoutput,4.0,1,0,26,6,81, ,4,0.20126719999999998,0.01,211,507.0,True,True,True,0,0,0
mystery_easy,prob09.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14252,depot_walker_sameoutput,8.0,1,2,76,18,308, ,8,0.2641105,0.01,205,391.0,True,True,True,0,0,0
mystery_easy,prob11.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10672,depot_walker_sameoutput,7.0,1,1,59,14,56, ,7,0.05,0.01,110,141.0,True,True,True,0,0,0
mystery_easy,prob19.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,22600,depot_walker_sameoutput,6.0,1,0,62,15,368, ,6,0.7386090000000001,0.0171035,465,928.0,True,True,True,0,0,0
mystery_easy,prob20.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,25868,depot_walker_sameoutput,7.0,1,0,34,8,241, ,7,0.8362474,0.0137095,462,979.0,True,True,True,0,0,0
mystery_easy,prob25.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,4.0,1,0,26,6,37, ,4,0.04,0.01,43,112.0,True,True,True,0,0,0
mystery_easy,prob26.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13172,depot_walker_sameoutput,6.0,1,0,38,9,113, ,6,0.1704327,0.01,174,356.0,True,True,True,0,0,0
mystery_easy,prob27.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12256,depot_walker_sameoutput,5.0,1,0,34,8,81, ,5,0.1250284,0.01,152,226.0,True,True,True,0,0,0
mystery_easy,prob28.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,11.0,1,0,70,17,66, ,11,0.04,0.01,78,127.0,True,True,True,0,0,0
mystery_easy,prob29.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12424,depot_walker_sameoutput,4.0,1,0,30,7,63, ,4,0.146993,0.01,177,252.0,True,True,True,0,0,0
mystery_easy,prob30.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,19056,depot_walker_sameoutput,11.0,1,0,118,29,539, ,11,0.48788909999999996,0.0261211,319,664.0,True,True,True,0,0,0
satellite_easy,p01-pfile1.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,9.0,1,0,38,9,70, ,9,0.02,0.01,17,105.0,True,True,True,0,0,0
satellite_easy,p02-pfile2.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,13.0,1,0,58,14,124, ,13,0.02,0.01,25,108.0,True,True,True,0,0,0
satellite_easy,p03-pfile3.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,11.0,1,0,46,11,208, ,11,0.04,0.01,42,127.0,True,True,True,0,0,0
satellite_easy,p04-pfile4.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,21.0,1,0,110,27,562, ,21,0.03,0.01,50,128.0,True,True,True,0,0,0
satellite_easy,p05-pfile5.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10536,depot_walker_sameoutput,22.0,1,0,166,41,1393, ,22,0.05,0.01,84,175.0,True,True,True,0,0,0
satellite_easy,p06-pfile6.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10540,depot_walker_sameoutput,20.0,1,0,98,24,819, ,20,0.05,0.01,73,161.0,True,True,True,0,0,0
satellite_easy,p07-pfile7.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10668,depot_walker_sameoutput,23.0,1,0,94,23,1155, ,23,0.06999999999999999,0.01,102,161.0,True,True,True,0,0,0
satellite_easy,p08-pfile8.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11044,depot_walker_sameoutput,29.0,1,0,134,33,2091, ,29,0.0910542,0.01,128,205.0,True,True,True,0,0,0
satellite_easy,p09-pfile9.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11308,depot_walker_sameoutput,37.0,1,0,206,51,3920, ,37,0.1255322,0.01,149,257.0,True,True,True,0,0,0
satellite_easy,p10-pfile10.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11596,depot_walker_sameoutput,35.0,1,0,238,59,5256, ,35,0.1285023,0.01,161,278.0,True,True,True,0,0,0
satellite_easy,p11-pfile11.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,12656,depot_walker_sameoutput,37.0,1,0,210,52,5290, ,37,0.1696268,0.01,168,286.0,True,True,True,0,0,0
satellite_easy,p12-pfile12.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13860,depot_walker_sameoutput,43.0,1,0,202,50,6427, ,43,0.2493788,0.0122826,213,366.0,True,True,True,0,0,0
satellite_easy,p13-pfile13.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,16312,depot_walker_sameoutput,76.0,1,0,1198,299,45725, ,76,0.4119412,0.0686259,244,567.0,True,True,True,0,0,0
satellite_easy,p14-pfile14.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,14372,depot_walker_sameoutput,44.0,1,0,194,48,7444, ,44,0.3155195,0.0142235,242,430.0,True,True,True,0,0,0
satellite_easy,p15-pfile15.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15804,depot_walker_sameoutput,52.0,1,0,326,81,16849, ,52,0.41154609999999997,0.0257642,328,598.0,True,True,True,0,0,0
satellite_easy,p16-pfile16.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17040,depot_walker_sameoutput,56.0,1,0,418,104,27170, ,56,0.5472366,0.0351563,400,713.0,True,True,True,0,0,0
satellite_easy,p17-pfile17.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17348,depot_walker_sameoutput,47.0,1,0,226,56,17365, ,47,0.5503056,0.0239403,454,687.0,True,True,True,0,0,0
satellite_easy,p18-pfile18.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,13352,depot_walker_sameoutput,34.0,1,0,150,37,4724, ,34,0.2458015,0.01,211,381.0,True,True,True,0,0,0
satellite_easy,p19-pfile19.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,15092,depot_walker_sameoutput,75.0,1,0,358,89,11447, ,75,0.32005720000000004,0.0226672,289,478.0,True,True,True,0,0,0
satellite_easy,p20-pfile20.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17660,depot_walker_sameoutput,106.0,1,0,2274,568,74680, ,106,0.43322,0.114331,329,526.0,True,True,True,0,0,0
zenotravel_easy,p01.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,1.0,1,0,10,2,7, ,1,0.04,0.01,18,205.0,True,True,True,0,0,0
zenotravel_easy,p02.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10272,depot_walker_sameoutput,8.0,1,0,46,11,46, ,8,0.03,0.01,18,113.0,True,True,True,0,0,0
zenotravel_easy,p03.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,6.0,1,0,66,16,265, ,6,0.05,0.01,40,121.0,True,True,True,0,0,0
zenotravel_easy,p04.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10404,depot_walker_sameoutput,9.0,1,0,102,25,246, ,9,0.04,0.01,40,137.0,True,True,True,0,0,0
zenotravel_easy,p05.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10532,depot_walker_sameoutput,12.0,1,0,154,38,462, ,12,0.060000000000000005,0.01,46,203.0,True,True,True,0,0,0
zenotravel_easy,p06.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10532,depot_walker_sameoutput,14.0,1,0,130,32,469, ,14,0.060000000000000005,0.01,52,163.0,True,True,True,0,0,0
zenotravel_easy,p07.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,10532,depot_walker_sameoutput,16.0,1,0,158,39,320, ,16,0.060000000000000005,0.01,52,149.0,True,True,True,0,0,0
zenotravel_easy,p08.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11020,depot_walker_sameoutput,15.0,1,0,222,55,1296, ,15,0.10241729999999999,0.01,84,281.0,True,True,True,0,0,0
zenotravel_easy,p09.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11184,depot_walker_sameoutput,25.0,1,0,182,45,1011, ,25,0.11251130000000001,0.01,92,205.0,True,True,True,0,0,0
zenotravel_easy,p10.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11332,depot_walker_sameoutput,29.0,1,0,378,94,2274, ,29,0.1271122,0.01,100,222.0,True,True,True,0,0,0
zenotravel_easy,p11.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11552,depot_walker_sameoutput,18.0,1,0,186,46,1776, ,18,0.15611780000000003,0.01,102,306.0,True,True,True,0,0,0
zenotravel_easy,p12.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11712,depot_walker_sameoutput,24.0,1,0,262,65,2003, ,24,0.15924570000000002,0.01,111,264.0,True,True,True,0,0,0
zenotravel_easy,p13.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,11732,depot_walker_sameoutput,32.0,1,0,514,128,4148, ,32,0.1740165,0.0131847,120,255.0,True,True,True,0,0,0
zenotravel_easy,p14.pddl,sameoutput,['run.err: sh: 1: ../../P7Requirements/downward/builds/release/bin/translate/translate.py: not found\nsh: 1: cannot open output.sas: No such file\n'],success,17404,depot_walker_sameoutput,37.0,1,0,606,151,13385, ,37,0.7259848,0.0474942,220,949.0,True,True,True,0,0,0
